# Generated by Django 4.2.3 on 2023-07-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_xailoxshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='xailox',
            table='xailox',
        ),
    ]
