# Generated by Django 4.2.3 on 2023-08-17 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_xailoxshop', '0002_alter_xailox_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='xailox',
            name='image',
            field=models.ImageField(default='', upload_to='xailoxshop/', verbose_name='изображение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='xailox',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='пользователь'),
            preserve_default=False,
        ),
    ]
